from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from datetime import datetime

from app.database import get_db
from app.routers.dashboard import get_lake_dashboard

router = APIRouter(prefix="/api/reports", tags=["Executive Reports"])

@router.get("/{lake_id}")
def generate_lake_report(lake_id: int, db: Session = Depends(get_db)):
    dash = get_lake_dashboard(lake_id=lake_id, db=db)
    
    report_data = {
        "report_id": f"JD-REP-{lake_id}-{datetime.utcnow().strftime('%Y%m%d%H%M')}",
        "generated_at": datetime.utcnow().isoformat(),
        "platform": "Jaal Drushti - AI Lake Water Intelligence",
        "lake_overview": {
            "name": dash.lake.name,
            "location": dash.lake.location,
            "coordinates": {
                "latitude": dash.lake.latitude,
                "longitude": dash.lake.longitude
            },
            "total_basin_area_km2": dash.lake.area_km2,
            "description": dash.lake.description
        },
        "current_status": {
            "wqi_score": dash.current_wqi,
            "wqi_category": dash.wqi_category,
            "wqi_color": dash.wqi_color,
            "wqi_30d_change_pct": dash.wqi_change_pct,
            "monitoring_status": dash.monitoring_status
        },
        "satellite_intelligence": {
            "observation_date": dash.satellite_latest.observation_date,
            "water_coverage_percentage": dash.water_coverage_percentage,
            "estimated_water_area_km2": dash.estimated_water_area_km2,
            "water_detection_status": dash.satellite_latest.water_detection_status,
            "sensor_source": dash.satellite_latest.source,
            "ai_interpretation": dash.ai_satellite_analysis
        },
        "physicochemical_readings": [
            {
                "parameter": p.name,
                "value": p.value,
                "unit": p.unit,
                "status": p.status,
                "relative_trend": p.mini_trend,
                "delta_pct": p.change_pct
            }
            for p in dash.parameters
        ],
        "parameter_sub_index_breakdown": [
            ps.dict() for ps in dash.parameter_scores
        ],
        "ai_predictive_forecast": {
            "current_wqi": dash.forecast.current_wqi,
            "predicted_7d_wqi": dash.forecast.predicted_7d_wqi,
            "net_change_points": dash.forecast.change_points,
            "model_confidence": f"{dash.forecast.confidence_score}%",
            "risk_assessment": dash.forecast.risk_level,
            "forecast_trajectory": [ft.dict() for ft in dash.forecast.forecast_trajectory],
            "expert_explanation": dash.forecast.explanation
        },
        "active_early_warnings": [
            {
                "type": a.alert_type,
                "severity": a.severity,
                "title": a.title,
                "message": a.message,
                "recommended_action": a.recommended_action
            }
            for a in dash.active_alerts
        ],
        "regulatory_recommendations": [
            "Maintain continuous telemetry at active sensor stations.",
            "Establish perimeter silt retention zones where runoff is elevated.",
            "Enforce CPCB Class C / WHO freshwater compliance standards on perimeter inlets.",
            "Report monthly water extent deltas to State Lake Conservation and Management Authority."
        ],
        "disclaimer": "Generated by Jaal Drushti prototype for hackathon demonstration and authorized environmental intelligence."
    }
    return report_data
